---
- name: Install Dovecot
  become: true
  tags: dovecot
  block:
    - name: Install
      apt:
        name:
          - dovecot-core
          - dovecot-imapd
          - dovecot-lmtpd
          - dovecot-sieve
        update_cache: true

    - name: Configure mail driver
      lineinfile:
        path: /etc/dovecot/conf.d/10-mail.conf
        regexp: "^mail_driver"
        line: "mail_driver = {{ dovecot_mailbox_driver }}"
        mode: "0644"
      notify: Reload Dovecot

    - name: Configure mail path
      lineinfile:
        path: /etc/dovecot/conf.d/10-mail.conf
        regexp: "^mail_path"
        line: "mail_path = {{ dovecot_mailbox_path }}"
        mode: "0644"
      notify: Reload Dovecot

    - name: Configure inbox path
      lineinfile:
        path: /etc/dovecot/conf.d/10-mail.conf
        regexp: "^mail_inbox_path"
        line: "mail_inbox_path = {{ dovecot_inbox_path }}"
        mode: "0644"
      notify: Reload Dovecot

    - name: Configure user name format for authentication
      lineinfile:
        path: /etc/dovecot/conf.d/10-auth.conf
        regexp: "^auth_username_format"
        line: "auth_username_format = {{ dovecot_auth_username_format }}"
        mode: "0644"
      notify: Reload Dovecot

    - name: Setup LMTP socket in Postfix
      blockinfile:
        path: /etc/dovecot/conf.d/10-master.conf
        insertafter: "^service lmtp"
        block: |
          unix_listener /var/spool/postfix/private/dovecot-lmtp {
            group = postfix
            mode = 0600
            user = postfix
          }
        mode: "0644"
      notify: Restart Dovecot

    - name: Setup sieve (LDA)
      blockinfile:
        path: /etc/dovecot/conf.d/15-lda.conf
        insertafter: "^protocol lda"
        block: |
          mail_plugins {
            sieve = yes
          }
        mode: "0644"
      notify: Reload Dovecot

    - name: Setup sieve (LMTP)
      blockinfile:
        path: /etc/dovecot/conf.d/20-lmtp.conf
        insertafter: "^protocol lmtp"
        block: |
          mail_plugins {
            sieve = yes
          }
        mode: "0644"
      notify: Reload Dovecot

    - name: Setup SSL certificate
      lineinfile:
        path: /etc/dovecot/conf.d/10-ssl.conf
        search_string: ssl_server_cert_file = /etc/dovecot/private/dovecot.pem
        line: "ssl_server_cert_file = {{ dovecot_ssl_server_cert_file }}"
        mode: "0644"
      when: dovecot_ssl_server_cert_file is defined
      notify: Restart Dovecot

    - name: Setup SSL key
      lineinfile:
        path: /etc/dovecot/conf.d/10-ssl.conf
        search_string: ssl_server_key_file = /etc/dovecot/private/dovecot.key
        line: "ssl_server_key_file = {{ dovecot_ssl_server_key_file }}"
        mode: "0644"
      when: dovecot_ssl_server_key_file is defined
      notify: Restart Dovecot

    - name: Manage service
      service:
        name: dovecot
        enabled: "{{ dovecot_service_enabled }}"
        state: "{{ dovecot_service_state }}"
